/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pokernight.gui;

import java.awt.*;
import javax.swing.*;
import java.io.*;
import javax.imageio.ImageIO;
/**
 *
 * @author dufresnec
 */
public class PokerTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form PokerTablePanel
     */
    public PokerTablePanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        InputStream inStream = getClass().getResourceAsStream("/resources/ft_green_poker_skin.png");
        try
        {
            g2d.drawImage(ImageIO.read(inStream), 100, 100, null);
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
